export interface ChatSession {
  id: string
  title: string
  messageCount: number
  createdAt: string
  updatedAt: string
}

export interface ChatMessage {
  id: string
  role: 'user' | 'assistant' | 'system'
  content: string
  toolCalls?: ToolCall[]
  references?: SourceReference[]
  createdAt: string
}

export interface StreamChunk {
  type: 'text' | 'tool_call' | 'tool_result' | 'error' | 'done'
  content?: string
  traceId?: string
  toolCall?: ToolCall
  toolName?: string
  result?: unknown
  message?: string
}

export interface ToolCall {
  toolName: string
  args: Record<string, unknown>
  result?: unknown
  status: 'pending' | 'running' | 'completed' | 'failed'
}

export interface SourceReference {
  chunkId: string
  documentName: string
  content: string
  score?: number
}

/** Single quiz question generated by agent quizGeneration tool */
export interface AgentQuizQuestion {
  id?: number           // 持久化后的数据库 ID，有则调 submitAnswer 入库
  question: string
  options: Record<string, string>
  answer: string
  explanation: string
}

/** Result of auto-grading (matches AutoGradingTool.GradeResult) */
export interface AgentGradingResult {
  score: number
  comment: string
  missing?: string
}

/** Knowledge graph node for the study studio panel */
export interface KnowledgeNode {
  id: string
  label: string
  children?: string[]
  mastery?: number
  color?: string
}

/** Reference item in study panel */
export interface StudyReference {
  id: number
  title: string
  source: 'knowledge' | 'chat'
  url?: string
}
